### ISSUE TITLE
Data read error during testing

### ISSUE THREAD

**Issue by Drangonliao123** [arimousa/DDAD#15]
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "E:\SoftWare\anaconda3\envs\lsomer\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "E:\SoftWare\anaconda3\envs\lsomer\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\SoftWare\anaconda3\envs\lsomer\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Code\Anomaly_Detection\DDAD-main\dataset.py", line 67, in __getitem__
    target = Image.open(
  File "E:\SoftWare\anaconda3\envs\lsomer\lib\site-packages\PIL\Image.py", line 3227, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/MVTec\\bottle\\test\\broken_large\\000_mask.png'

When I test mine, the above error occurs. There is no 000_mask.png under MVTec\\bottle\\\test\\\broken_large\\\path.

**Comment by Kusunoki0130** [comment]
You can open dataset.py and remove "/"  in line 66 and 77.

**Comment by Drangonliao123** [comment]
> You can open dataset.py and remove "/" in line 66 and 77.

Thank you very much, the error has been solved!

**Comment by fl0308** [comment]
> You can open dataset.py and remove "/" in line 66 and 77.

thank you!
